name: Flink

services:
  jobmanager:
    image: flink:1.20-paimon-1.2.0
    container_name: flink-jobmanager
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2048m
        parallelism.default: 1
    ports:
      - "28081:8081"
    command: jobmanager
    volumes:
      - ./flink/jobs:/opt/flink/jobs
    deploy:
      replicas: 1

  taskmanager:
    image: flink:1.20-paimon-1.2.0
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2

  client:
    image: flink:1.20-paimon-1.2.0
    container_name: flink-client
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    depends_on:
      - jobmanager
    command: tail -f /dev/null
    volumes:
      - ./flink/jobs:/opt/flink/jobs