name: Flink

services:
  jobmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    image: compute-flink-cluster
    container_name: jobmanager
    ports:
      - "18081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2048m
        parallelism.default: 3
    volumes:
      - ./logs/paimon:/tmp/paimon
  taskmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    image: compute-flink-cluster
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m
    volumes:
      - ./logs/paimon:/tmp/paimon
  sql-client:
    build:
      context: ./
      dockerfile: Dockerfile
    image: compute-flink-cluster
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager