name: Flink

services:
  jobmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    container_name: flink-jobmanager
    ports:
      - "18081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2048m
        parallelism.default: 3

  taskmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 12
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m

  sql-client:
    build:
      context: .
      dockerfile: flink/Dockerfile
    container_name: flink-sql-client
    depends_on:
      - jobmanager
    command: tail -f /dev/null  # 保持容器运行 ; docker exec -it sql-client bin/sql-client.sh embedded
    tty: true
    stdin_open: true
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager