name: Flink

services:
  jobmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    container_name: flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2048m
        parallelism.default: 3
    ports:
      - "18081:8081"
    command: jobmanager
    volumes:
      - ./flink/jobs/job.sql:/opt/flink/job.sql
    deploy:
      replicas: 1

  taskmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 12
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2

  sql-client:
    build:
      context: .
      dockerfile: flink/Dockerfile
    container_name: flink-sql-client
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    depends_on:
      - jobmanager
    command: tail -f /dev/null  # 保持容器运行 ; docker exec -it sql-client bin/sql-client.sh embedded
    tty: true
    stdin_open: true